#!/bin/sh
set -ex
mkdir -p `pwd`/dist
chmod 777 `pwd`/dist
docker build -t docker-compose .
docker run -u user -v `pwd`/dist:/code/dist --rm --entrypoint pyinstaller docker-compose -F bin/docker-compose
mv dist/docker-compose dist/docker-compose-`uname -s`-`uname -m`
docker run -u user -v `pwd`/dist:/code/dist --rm --entrypoint dist/docker-compose-`uname -s`-`uname -m` docker-compose --version
